import Seo from '@/components/Seo'
import App from '@/components/App'
import Navbar from '@/components/Navbar'

export default function RootLayout({ children }) {
  return (
    <>
      <Seo title="Create Next App" description="Generated by create next app" />
      <App>
        <Navbar />
        {children}
      </App>
    </>
  )
}
